name: package
on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-latest
          - ubuntu-latest

jobs:
  package:
    if: github.repository_owner == 'HATTER-LONG'
    runs-on: ["${{ inputs.chosen-os }}"]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'AstroNvim/AstroNvim'
          path: '${HOME}/.config/nvim'
      - uses: actions/checkout@v3
        with:
          path: '${HOME}/.config/nvim/lua/user'
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: Run 
        timeout-minutes: 10
        run: |
          nvim +qa
          nvim --headless "+Lazy! update" +qa
          cd ${HOME}/.config
          tar -cvzf AstroNvimDots.tar.gz ./nvim ${HOME}/.local/share/nvim ${HOME}/.local/state/nvim 
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ~/.config/AstroNvimDots.tar.gz
